import React from 'react'
import Head from 'next/head';
import {
    Container,
    Grid,
    Header,
    Icon
} from 'semantic-ui-react'

function Home() {
    return (
        <>
            <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
        <main>
            <Container>
                <Grid centered columns={1}>
                    <Grid.Column>
                        <Header as='h1' textAlign='center'>
                            <Icon name='terminal' />
                            Welcome to the Next.js Semantic Starter Kit!
                        </Header>
                    </Grid.Column>
                </Grid>
                <Grid centered columns={1}>
                    <div className="ball"></div>
                </Grid>
            </Container>
        </main>
        </>
    );
}

export default Home;